<?php return array (
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'backend\\Controllers\\auth' => 'modules/backend/controllers/auth.php',
  'backend\\Controllers\\index' => 'modules/backend/controllers/index.php',
  'system\\Controllers\\settings' => 'modules/system/controllers/settings.php',
  'cms\\Controllers\\themes' => 'modules/cms/controllers/themes.php',
  'cms\\Controllers\\index' => 'modules/cms/controllers/index.php',
  'rainlab\\user\\Plugin' => 'plugins/rainlab/user/Plugin.php',
  'robotron\\opiniopedia\\Plugin' => 'plugins/robotron/opiniopedia/Plugin.php',
  'RainLab\\User\\Classes\\UserRedirector' => 'plugins/rainlab/user/classes/UserRedirector.php',
  'RainLab\\User\\Components\\Session' => 'plugins/rainlab/user/components/Session.php',
  'RainLab\\User\\Facades\\Auth' => 'plugins/rainlab/user/facades/Auth.php',
  'RainLab\\User\\Classes\\AuthManager' => 'plugins/rainlab/user/classes/AuthManager.php',
  'RainLab\\User\\Models\\Settings' => 'plugins/rainlab/user/models/Settings.php',
  'RainLab\\User\\Components\\Account' => 'plugins/rainlab/user/components/Account.php',
  'RainLab\\User\\Components\\ResetPassword' => 'plugins/rainlab/user/components/ResetPassword.php',
  'RoBotron\\Opiniopedia\\Components\\newpost' => 'plugins/robotron/opiniopedia/components/newpost.php',
  'robotron\\opiniopedia\\Controllers\\Pedia' => 'plugins/robotron/opiniopedia/controllers/Pedia.php',
  'RoBotron\\Opiniopedia\\Models\\Opinio' => 'plugins/robotron/opiniopedia/models/Opinio.php',
  'rainlab\\user\\Controllers\\users' => 'plugins/rainlab/user/controllers/users.php',
  'RainLab\\User\\Models\\User' => 'plugins/rainlab/user/models/User.php',
  'RainLab\\User\\Models\\UserGroup' => 'plugins/rainlab/user/models/UserGroup.php',
  'RoBotron\\opiniopedia\\models\\Opinio' => 'plugins/robotron/opiniopedia/models/Opinio.php',
  'robotron\\opiniopedia\\Controllers\\pedia' => 'plugins/robotron/opiniopedia/controllers/pedia.php',
);